# This Docker file is aimed to test the install-dotfiles.sh script
FROM ubuntu:latest
ENV DEBIAN_FRONTEND noninteractive
MAINTAINER Adroaldo de Andrade <adroaldof@gmail.com>

# Set working directory to /root folder
WORKDIR /root

# Copy dotfiles bash script installer
COPY install-dotfiles.sh install-dotfiles.sh

# Run bash script install
RUN . ./install-dotfiles.sh

